// src/app/layout.tsx

import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "./_components/topnav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { Toaster } from "~/components/ui/sonner";
import { PostHogProvider } from "./analytics/providers";

export const metadata: Metadata = {
  title: "PET GALLERY",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "https://u4ocvzai6f.ufs.sh/f/5zX1RPP9E6ct4q5lAupGMuzlwvB8sUkRFYHK9iINTfe6LnAX" }],
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        
        <body>
          <PostHogProvider>
          <div className="grid h-screen grid-rows-[auto,1fr]">
            <TopNav />
            <main className="overflow-y-scroll">{children}</main>
          </div>
          {modal}
          <div id="modal-root"></div>
          <Toaster />
          </PostHogProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}