import "~/styles/globals.css";
import {ClerkProvider, SignedOut,} from '@clerk/nextjs'
import "@uploadthing/react/styles.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Topnav from "./_components/topnav";
import Carousel from "./_components/carousel";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { ourFileRouter } from "./api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
import { Toaster } from "~/components/ui/sonner";
import { PostHogProvider } from "./analytics/providers";


export const metadata: Metadata = {
  title: "cardepot",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geist.variable} dark `}>
      <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <body>
        <PostHogProvider>
            <div>
              <Topnav />    
              <main className=" ">
                {children}
              </main>
            </div>
            {modal}
            <div id="modal-root"></div>
            <Toaster/>
          <SignedOut>
            <Carousel />
          </SignedOut>
        </PostHogProvider>
        </body>
      </html>
    </ClerkProvider>
  );
  
}


